---
swagger: '2.0'
info:
  description: 'API documentation for the SwiftWise Inventory Management System.'
  version: '1.0.0'
  title: 'SwiftWise API'
  termsOfService: 'http://swiftwise.com/terms/'
  contact:
    email: 'support@swiftwise.com'
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'z0a6v7mgd2.execute-api.us-west-2.amazonaws.com'
basePath: '/dev'
tags:
- name: 'auth'
  description: 'Endpoints for user authentication and authorization'
- name: 'user'
  description: 'Endpoints for managing user profiles'
- name: 'product'
  description: 'Endpoints for managing products in the inventory system'
- name: 'category'
  description: 'Endpoints for managing product categories'
- name: 'unit'
  description: 'Endpoints for managing units of measurement for products'
- name: 'sales'
  description: 'Endpoints for managing sales and sales items'
schemes:
- 'https'
paths:

definitions:

externalDocs:
  description: 'Find out more about Swagger'
  url: 'http://swagger.io'
